### PR TITLE
Function: stat_summary, tests & add pytest to env

### PR DESCRIPTION
**Pull request by beth-ouyang**
1. Finished the function `stat_summary`
- file: `src/dscigametrics/stat_summary.py`
2. Finished the test for `stat_summary`
- file: `tests/test_statsummary.py`
3. Update poetry files to add `pytest`

### CODE REVIEW

**Comment by WeilinHan8** [comment]
What's your code coverage?

**Review by WeilinHan8 — CHANGES_REQUESTED** [review]
I think you should add test for input type

**Comment by beth-ouyang** [comment]
> I think you should add test for input type

I have added some additional tests related to the input type and edge (all 0s situation) in the latest commit~

**Review by WeilinHan8 — CHANGES_REQUESTED** [review]
Could you add more inline comment in your function file to explain what each step is doing?

**Comment by beth-ouyang** [comment]
@WeilinHan8  Hi! The inline comments are add to my function `stat_summary.py`.
Also, I included the `environment.yml` in this branch. (Further discussions will be on slack channel later)

**Pull request closed without merging**
